name: Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build container
        run: docker-compose build

      - name: Test
        run: docker-compose run --rm test
